### ISSUE TITLE
Calculator page crash after changing a asset level.

### ISSUE THREAD

**Issue by ruiaraujo012** [ruiaraujo012/fx-clash-stats-web#40]
No clue yet about what it is.

**Comment by Arc891** [comment]
Can confirm this bug happening to me as well, any time I set a part or driver's level back to 0, going to the calculator gives me an error page. Haven't been able to find anything it might be related to like a specific error message, but perhaps the calculator is still trying to calculate the score of a part when its level has been set to 0 and this throws an error somewhere?

**Comment by ruiaraujo012** [comment]
I have the same thought, I'm thinking about connecting this app to a log service like Sentry to catch these errors.
