### ISSUE TITLE
Price for upgrade needs att

### ISSUE THREAD

**Issue by GuiCruz7** [ruiaraujo012/fx-clash-stats-web#49]
### Prerequisites

- [ x ] Did you search for related issues?

**Describe the bug**
The price show to upgrade fernando alonso rare is wrong

**To Reproduce**

put fernando alonso on lvl 1, add 4 cards

**Expected behavior**

expected the price to be 155,000 to upgrade for lvl 2 , but its shows 279,000

**Screenshots**

**Additional context**

**Comment by GuiCruz7** [comment]
![image](https://github.com/ruiaraujo012/fx-clash-stats-web/assets/144031404/05ddb491-139b-4a69-9981-addaa70e8e62)

![image](https://github.com/ruiaraujo012/fx-clash-stats-web/assets/144031404/176b5b23-fc89-4b19-94e2-6deb5373b302)

**Comment by ruiaraujo012** [comment]
You're right, sorry about that, should be fixed now #51.

Please make sure you have the v1.0.8, if not, refresh your page until you have it.
